const FILE_OR_FOLDER_NAME_VARIABLES_REGEX = /[^\%]+(?=\%)/;
const TEMPLATE_FILE_EXTENSION_REGEX = /\.(tpl|eta)$/;
const THEME_CONFIG_FILE_NAME = "_config.json";
const THEME_FALLBACK_TEMPLATE_NAME = "page";

export {
    FILE_OR_FOLDER_NAME_VARIABLES_REGEX as FILE_OR_FOLDER_NAME_VARIABLES,
    TEMPLATE_FILE_EXTENSION_REGEX,
    THEME_CONFIG_FILE_NAME,
    THEME_FALLBACK_TEMPLATE_NAME,
};
